# CIRV jobs
#
# On Merge requests, tags and merges:
#   - Run tox
#   - Build documentation
---
include:
  - project: anuket/releng
    file: '/gitlab-templates/RTD.gitlab-ci.yml'

cirv-verify:
  stage: build
  image: python:3
  interruptible: true
  before_script:
    - pip install tox
  script:
    - tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
